[package]
name = "doteur_wasm"
version = "0.1.3"
edition = "2021"
readme = "README.md"


[lib]
crate-type = ["cdylib"]

[dependencies]
doteur_core = { path = "../doteur_core", default-features = false, version="0.5.3" }
wasm-bindgen = "0.2.92"
wasm-logger = "0.2.0"
