[package]
name = "doteur_wasm"
version = "0.1.1"
edition = "2021"
readme = "README.md"


[lib]
crate-type = ["cdylib"]

[dependencies]
doteur_core = { path = "../doteur_core", default-features = false, version="0.5.2" }
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"
