name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extra steps to have it working with github
        run:  mkdir ~/.ruby ; echo 'export GEM_HOME=~/.ruby/' >> ~/.bashrc; echo 'export PATH="$PATH:~/.ruby/bin"' >> ~/.bashrc; source ~/.bashrc
      - name: Install jekyll and bundle
        run: gem install jekyll bundler
      - name: Go to docs dir
        run: cd docs 
      - name: Install jekyll gems
        run: bundle install
      - name: Build out
        run: bundle exec jekyll b
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ../_site
    
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
